### ISSUE TITLE
New P01 request - "Remote-sensing reflectance of the water body" (BODCNVS-1392)

### ISSUE THREAD

**Issue by robthomas-marine** [nvs-vocabs/P01#125]
Please could a new S06 (i.e. property) term for “Remote-sensing reflectance” be created and then used in combination with the S26 matrix “water body” to create a P01 term "Remote-sensing reflectance of the water body"?

Definition below: 
Remote sensing reflectance (Rrs, units: sr−1) is defined as the ratio of water-leaving radiance (Lw, units: µW cm−2 sr−1 nm−1) to downwelling irradiance just above the sea surface (Es, units: µW cm−2 nm−1) (O’Reilly et al., 1998). 

This would be an equivalent P01 term for the CF standard name (P07)
CFV13N26 
surface_ratio_of_upwelling_radiance_emerging_from_sea_water_to_downwelling_radiative_flux_in_air 
 
Units are "per steradian" (P06: PSTR)

Thanks

**Comment by roy-lowry** [comment]
I initially thought that having 'remote sensing' in an entity name was a bad idea until I read the CF definition and the NASA description of the parameter at https://oceancolor.gsfc.nasa.gov/atbd/rrs/ .  I reckon both the standard name and O'Reilly et al relate to the NASA algorithm, although the algorithm could have changed over time.
In the NASA algorithm remote sensing reflectance (Rrs) is calculated by dividing the water leaving radiance (normalised water-leaving radiance nLw rather than Lw)  for radiation of a single-wavelength at a single angle (vertical) by the downwelling vector irradiance (computed from mean extraterrestrial solar irradiance) at that wavelength. 
P01 codes using 'remote sensing reflectance' should either have the wavelength specified (makes the units nm-1 sr-1) or an explicit statement somewhere (definition?) that wavelength is unspecified (units sr-1). 
In CF the standard name is for 'Rrs at unspecified wavelength(s)'  which has units sr-1. Wavelength(s) are then specified as an additional co-ordinate.

**Comment by robthomas-marine** [comment]
Thanks Roy. Apologies I should have specified the "unspecified wavelength" or "wavelength specified elsewhere in metadata".

We'd prefer to go that route that having a parameter every 2 nm in the range 320-900nm.

**Comment by roy-lowry** [comment]
Would have loved to have gone down that route in the past - P01 would be a lot slimmer - but was constrained by QXF and the sample schema data model!!

**Comment by gwemon** [comment]
So could the modelisation of the new term according to the P01 semantic model be:
Remote sensing reflectance (new term to be created in S06)
of
[electromagnetic radiation (unspecified single wavelength)](http://vocab.nerc.ac.uk/collection/S29/current/PE000770/)
[from the](http://vocab.nerc.ac.uk/collection/S02/current/S025/) 
[water body](http://vocab.nerc.ac.uk/collection/S26/current/MAT00640/)?

**Comment by robthomas-marine** [comment]
Hi,

Is there a time-line for this code to be added? It is needed for a dataset we've been asked to publish with a DOI.

Cheers
Rob

**Comment by gwemon** [comment]
Hi Rob, no there isn't but I'll try and get it done for you by Monday. Cheers, Gwen.

**Comment by robthomas-marine** [comment]
Hi Gwen,

Did you get a chance to publish this yesterday?

Cheers
Rob

**Comment by danibodc** [comment]
Hi @robthomas-marine, Gwen didn't manage to get to this but I am picking this up now.

Thanks!
Dani

**Comment by danibodc** [comment]
Hi @robthomas-marine, this has now been loaded to P01, I will confirm that it's live tomorrow morning.

**Code:** RRSPSTR1
**Pref label:** Remote sensing reflectance of electromagnetic radiation (unspecified single wavelength) {Rrs} from the water body
