### ISSUE TITLE
Request for new property - river water level (BODCNVS-1747)

### ISSUE THREAD

**Issue by danibodc** [nvs-vocabs/P01#202]
A request was received for a new P01 term to describe water level in rivers.

We propose to create a new P01 code that could possibly come under P02 http://vocab.nerc.ac.uk/collection/P02/current/RVDS/, if this was broadened to include river level.

At this stage we would need an understanding of what the reference point is for defining the water level of the river.

**Comment by roy-lowry** [comment]
Hi Dani,

I think river level gauges can be levelled against a terrestrial mapping datum. In the UK this is the zero height for Ordnance Survey maps which was - and I think still is - ODN (Ordnance Datum Newlyn), but each country will have their own, probably more than one.  This is exactly the same as for tide gauges - see the whole raft of P01 codes starting with 'Surface elevation (' such as http://vocab.nerc.ac.uk/collection/P01/current/ASLVODNP/. There is cover in these for tide gauges that haven't been been levelled into anything ([ASLVTGZP](http://vocab.nerc.ac.uk/collection/P01/current/ASLVTGZP). 

I think a similar set of P01 codes will be would be required for river levels, but the 'relative to instrument zero' generic code might be a good place to start.

**Comment by roy-lowry** [comment]
Light bulb moment.....

Couldn't 'Surface elevation (relative to instrument zero) of the water body by fixed in-situ pressure sensor' to a more generic 'Surface elevation (relative to instrument zero) of the water body' or if there was real pressure to do so with another instrument type appended cover the request for water levels in rivers?  The P02 mapping then becomes a bit of an issue - how does one enable separate discovery of sea level and river level data???? Only way would be to map a subset of the Surface elevation codes to a broadened RVDS (broadening it makes me uncomfortable as it's really about fluxes across a boundary) but that's getting very ugly. Maybe one shouldn't be able to discover them separately through a description of what was measured?  It can't be done for temperature or salinity.....

**Comment by danibodc** [comment]
We have been having some further discussion about this. We think it would be fine to have a new P02 term:
‘Lake and river water level parameters’

We would then model the P01 as follows:
‘Height of river water relative to ground surface.’

**Comment by danibodc** [comment]
AHRVGRS1	Height of river water relative to ground surface
