### ISSUE TITLE
NTR: Location (geographic coordinates) of spawning grounds (BODCNVS-1852)

### ISSUE THREAD

**Issue by roswri** [nvs-vocabs/P01#224]
Location (geographic coordinates) of spawning grounds of Clupea harengus (ITIS: 161722: WoRMS 126417)

If modelled in GP_MODEL
S06: S0600255 - Location (geographic coordinates)
S07: S0700006 - not specified
S29: *new term* Spawning grounds (Clupea harengus (ITIS: 161722: WoRMS 126417)) / Spawning grounds (biological entity specified elsewhere)
S18: *new term* - Spawning grounds
S19: *new term* - Clupea harengus (ITIS: 161722: WoRMS 126417) or biological entity specified elsewhere 
S02: S029 - not applicable
S26: MAT00906 - not applicable

**Comment by roswri** [comment]
@gwemon 
Since the plan is to add 'Spawning grounds' to S18, I think this P01 needs to be created using GP_MODEL, and the biological entity would need to be added to S19 so they can be combined to make the S29. Including the biological entity like this doesn't seen right, have I missed something?

It seems like the best way might be to make a generic term as: 'Location (geographic coordinates) of spawning grounds', with the description: 'Geographic coordinates indicating the location of spawning grounds of a biological entity specified elsewhere in the metadata.'

**Comment by gwemon** [comment]
@roswri there is a BIOENTRF in the GP model but I forgot that it is strictly related to MATRIX='BIOTA'. What you are proposing seems sensible but I need to think about the consequences of such generic term at the P01 level.

**Comment by gwemon** [comment]
@roswri I have created the new P01 term in the old biological model as a temporary measure. We will need to add a S29 field to the current biological model in order to be able to deal with this pattern of the property of a thing of a thing when the thing is not a matrix.
The code created is GLOCCHSG	Location (geographic coordinates) of spawning grounds of Clupea harengus (ITIS: 161722: WoRMS 126417) it is awaiting publication.
I let you make the amendments to the P02 code https://github.com/nvs-vocabs/P02/issues/15.

**Comment by roswri** [comment]
https://vocab.nerc.ac.uk/collection/P01/current/GLOCCHSG/
