### ISSUE TITLE
NTR: PAH concentrations in biota + weight and length of Solea solea and Squalus acanthias [9 terms] [BODCNVS-1995]

### ISSUE THREAD

**Issue by roswri** [nvs-vocabs/P01#237]
Concentration of IMS PAH mixture per unit dry weight of biota {Chamelea gallina (ITIS:   205649: WoRMS 141907) [Subcomponent: flesh]}
Concentration of IMS PAH mixture per unit wet weight of biota   {Ruditapes philippinarum (WoRMS 231750) [Subcomponent: flesh]}
Concentration of IMS PAH mixture per unit dry weight of biota   {Solea solea (ITIS: 173002: WoRMS 127160) [Subcomponent: muscle tissue]}
Concentration of IMS PAH mixture per unit dry weight of biota   {Squalus acanthias (ITIS: 160617: WoRMS 105923) [Subcomponent: muscle   tissue]}
Specimen weight standard deviation of Solea solea (ITIS: 173002:   WoRMS 127160)
Specimen weight of Squalus acanthias (ITIS: ...: WoRMS 105923)
Specimen weight standard deviation of Squalus acanthias (ITIS:   ...: WoRMS 105923)
Length of of Squalus acanthias (ITIS: ...: WoRMS 105923)
Length standard deviation of of Squalus acanthias (ITIS: ...:   WoRMS 105923)

**What would be its expected units of measure or its vector dimensions**
Concentrations - ng/g (NGPG)
Weights - g (UGRM)
Lengths - mm (UXMM)

**Comment by roswri** [comment]
S27 for 'IMS PAH mixture I' exists (http://vocab.nerc.ac.uk/collection/S27/current/CS003044/), but will need to check with the requestor if this is the same mixture

**Comment by roswri** [comment]
PAH in biota codes created, pending publication on NVS:
PAH07591 - Concentration of EPA 16 priority polycyclic aromatic hydrocarbons minus acenaphthylene {EPA 16-acenaphthylene} per unit dry weight of biota {Solea solea (ITIS: 173002: WoRMS 127160) [Subcomponent: muscle tissue]}
PAH07595 - Concentration of EPA 16 priority polycyclic aromatic hydrocarbons minus acenaphthylene {EPA 16-acenaphthylene} per unit dry weight of biota {Squalus acanthias (ITIS: 160617: WoRMS 105923) [Subcomponent: muscle tissue]}
PAH08962 - Concentration of EPA 16 priority polycyclic aromatic hydrocarbons minus acenaphthylene {EPA 16-acenaphthylene} per unit dry weight of biota {Chamelea gallina (ITIS: 205649: WoRMS 141907) [Subcomponent: flesh]}
PAH09181 - Concentration of EPA 16 priority polycyclic aromatic hydrocarbons minus acenaphthylene {EPA 16-acenaphthylene} per unit dry weight of biota {Ruditapes philippinarum (WoRMS 231750) [Subcomponent: flesh]}

**Comment by gwemon** [comment]
For the specimen weight and length, we need to create these terms using our PUV semantic model. So the terms would be of the form e.g.
Weight of analysed specimen of biota {named biological entity}
Length of analysed specimen of biota {named biological entity}
OR
Weight of sample of biota {named biological entity}
Length of sample of biota {named biological entity}

The use of the term "specimen" and how it is different from "sample" needs to be reassessed to ensure that it is not misunderstood.

Before going ahead I have a few questions @Marina:
- I understand these are the weight and length of the animals used for the EPA contamination analysis. Is that correct?
- and since it has a SD this is more than one animal - si the number given?
- also is it specified if the weight is wet weight or dry weight?
- and are we sure this is the average weight and length of the population of animals used for the analysisand not the weight of the analysed samplethe organism from which the sample was taken? I guess the later but we need to be sure.
- as for the length is it just "length" or is it qualified as e.g. Total length, Standard length, ?

**Comment by mlipizer** [comment]
I answer below:

1. I understand these are the weight and length of the animals used for the EPA contamination analysis. Is that correct? **YES**
2. and since it has a SD this is more than one animal - si the number given? YES (3 REPLICATES)
3. also is it specified if the weight is wet weight or dry weight? WET WEIGHT
4. and are we sure this is the average weight and length of the population of animals used for the analysis and not the weight of the analysed sample the organism from which the sample was taken? I guess the later but we need to be sure. THIS IS THE AVERAGE WEIGHT OR LENGTH OF THE SAMPLED ORGANISMS (example: 3 fish were sampled, weighted and then analyis of contaminant was done on all 3)
5. as for the length is it just "length" or is it qualified as e.g. Total length, Standard length, ? IT IS AVERAGE LENGHT
I do not understand what is meant by: specimen" and how it is different from "sample"

**Comment by gwemon** [comment]
Thank you @mlipizer so it is the weight and length of the organisms from which samples were taken for the analysis.
The distinction between "specimen" and "sample" is very difficult to make because the terms are used differently in different domains! We have terms in the NVS that use "specimen" but these have not yet been remodelled to the new semantic model. I will have a think through about how we can represent these measurements without ambiguity using the semantic model. I'll consult colleagues in and out of BODC too. What is you time scale for requiring these terms?

**Comment by mlipizer** [comment]
Thanks Gwen. Timing: if possible by end of next week. Thanks

**Comment by gwemon** [comment]
Created:
WETW1234	Wet weight of Squalus acanthias (ITIS: 160617: WoRMS 105923)
BLEN1234	Length of Squalus acanthias (ITIS: 160617: WoRMS 105923)

Remodeled:
"Specimen weight" codes converted using S06 property  "Wet weight"  (https://github.com/nvs-vocabs/P01/issues/245)

And created corresponding SD codes as follows:
SDTW1234	Wet weight standard deviation of Squalus acanthias (ITIS: 160617: WoRMS 105923)
SDEN1234	Length standard deviation of Squalus acanthias (ITIS: 160617: WoRMS 105923)
SDWTOX09	Wet weight standard deviation of Solea solea (ITIS: 173002: WoRMS 127160)

**Comment by gwemon** [comment]
[WETW1234](http://vocab.nerc.ac.uk/collection/P01/current/WETW1234/) Wet weight of Squalus acanthias (ITIS: 160617: WoRMS 105923)
[BLEN1234](http://vocab.nerc.ac.uk/collection/P01/current/BLEN1234/) Length of Squalus acanthias (ITIS: 160617: WoRMS 105923)
[SDTW1234](http://vocab.nerc.ac.uk/collection/P01/current/SDTW1234/) Wet weight standard deviation of Squalus acanthias (ITIS: 160617: WoRMS 105923)
[SDEN1234](http://vocab.nerc.ac.uk/collection/P01/current/SDEN1234/) Length standard deviation of Squalus acanthias (ITIS: 160617: WoRMS 105923)
[SDWTOX09](http://vocab.nerc.ac.uk/collection/P01/current/SDWTOX09/) Wet weight standard deviation of Solea solea (ITIS: 173002: WoRMS 127160)

**Comment by gwemon** [comment]
@mlipizer these terms are now all live on the NVS. Please re-open this ticket if there are any outstandibng issues. Many thanks.

**Comment by mlipizer** [comment]
Thanks for these codes. I need following related codes:
- Wet weight mean of Squalus acanthias (ITIS: 160617: WoRMS 105923)
- Length mean of Squalus acanthias (ITIS: 160617: WoRMS 105923)
- Wet weight mean of Solea solea (ITIS: 173002: WoRMS 127160)
- Length mean of Solea solea (ITIS: 173002: WoRMS 127160)

thanks

**Comment by gwemon** [comment]
@Mlipizer. The code I created are for one or multiple individuals. If multiple then the code is the mean. Maybe I need to make the definition clearer.

**Comment by mlipizer** [comment]
Thanks Gwen, I read the definition, it is clear. no need. thanks
