### ISSUE TITLE
NTR: Code requests for Marine Spatial Planning Support

### ISSUE THREAD

**Issue by adamml** [nvs-vocabs/P01#33]
1. Geographic location of human activity specified by classification to a term from the EMODnet Human Activities vocabulary (SDN::HA2)
   - I propose linking this to the P02 "Administrative units" term and we use HA2->P03->P08 mappings for discovery
   - P06 = UUUU
2. Description of habitat by classification to a term from the Marine Strategy Framework Directive broad habitat types (Commission Decision (EU) 2017/848)
    - See [SDN:P01::UKMH0405](http://vocab.nerc.ac.uk/collection/P01/current/UKMH0405/) as a prototype
    - I propose linking this to P02 Habitat Characterisation (HBCH)
    - P06 = UUUU
3. Area of habitat by classification to a term from the Marine Strategy Framework Directive broad habitat types (Commission Decision (EU) 2017/848)
    - I propose linking this to P02 Habitat Extent (HBEX)
    - P06 = UMSQ

Looping @conbon27; @robthomas-marine; @Elizabeth-Tray; @rcarr01; @dodriscoll; @flynnmechan; @tkeena

**Comment by gwemon** [comment]
Thank you @adamml The terms as proposed look suited to the P01 semantic model. I have a few questions about how we should define these terms. I'll start with the first one:

1- Geographic location. This will need to be defined in the [S06](http://vocab.nerc.ac.uk/collection/S06/current/) vocab.
How shall we define it? very broad or very strict? i..e do we limit it to coordinates of latitude and longitude or do we accept results as place names too? I think we need to go for the former. Do you agree?
In that case,  I would suggest changing the label "Geographic location" to make it less ambiguous.
Wiki GIS defines "Geographic coordinates" as a measurement of a location on the earth's surface expressed in degrees of latitude and longitude". [http://wiki.gis.com/wiki/index.php/GIS_Glossary/G, 2020Sep22]
So we could adapt this to create a new S06 as follows:
prefLabel: "Location (geographic coordinate system)"
definition: "A location on the earth's surface expressed in degrees of latitude and longitude and represented by a single pair of numbers (point representations), or as a collection of single pair of numbers (line, arc, polygon representations).
Would that fit your requirement?

**Comment by adamml** [comment]
"Location (geographic coordinate system)"

Looks good to me.

One comment I'd have is the Coordinate Reference System would also need defining elsewhere in the metadata (no problem as we do that anyway) but would that need to be explicit here? In the prefLabel or in the definition?

**Comment by gwemon** [comment]
I just realised my definition above is flawed because it says "expressed in degrees of latitude and longitude" which is too specific in this case.

So new iteration for the S06 term:
Location (geographic coordinate system) or maybe just simply "Location (geographic coordinates)"
defined as:
"A location on the earth's surface represented by a point, a line, an arc, or any other type of polygons defined by coordinates in a known Coordinate Reference System"

I am no geograph so please don't hesitate to correct!

**Comment by adamml** [comment]
That's a good spot @gwemon!

I like "Location (geographic coordinates)".

On the definition, a z-axis could be included so it may not be on the Earth's surface. Also, strictly speaking, the Coordinate Reference System can be for another astronomical body than the Earth. Maybe we could add a little to the end of the definitions well. Suggestion:

"A location relative to the surface of the Earth, or other planetary or stellar body, represented by a point, line, arc, or any other type of polygon and defined by encoding the coordinates of the location in a known Coordinate Reference System. Where possible the Coordinate Reference System used should be specified elsewhere in the metadata by a term from a well defined and managed register such as the European Petroleum Survey Group (EPSG) Geodetic Parameter Dataset."

**Comment by gwemon** [comment]
So, for the property, the term for "Location (geographic coordinates)" will be the only new term that needs to be added to S06 since we have [Description](http://vocab.nerc.ac.uk/collection/S06/current/S0600147/) and [Area](http://vocab.nerc.ac.uk/collection/S06/current/S0600146/) already defined.

For the main object we already have [habitat](http://vocab.nerc.ac.uk/collection/S29/current/PE001274/) defined but we will need a new term in S29 for "human activity". Unless anybody recommends something different, I will use the same definition as was [used in A01](http://vocab.nerc.ac.uk/collection/A01/current/Human_Activity/).

For the processing method element, we need to add the following 2 terms to [S05](https://www.bodc.ac.uk/resources/vocabularies/vocabulary_search/S05/):
"classification to a term from the EMODnet Human Activities vocabulary (SDN::HA2)"
"classification to a term from the Marine Strategy Framework Directive broad habitat types (Commission Decision (EU)2017/848)"
@adamml are the broad habitat types available online or defined in a documnet available online?

**Comment by gwemon** [comment]
Also for the Location and Description parameters I would recommend the unit to be http://vocab.nerc.ac.uk/collection/P06/current/XXXX/

**Comment by adamml** [comment]
Thanks @gwemon - this is looking good:

> @adamml are the broad habitat types available online or defined in a document available online?

The relevant Commission decision is here: https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:32017D0848&from=EN There's no real "definition" though, just the "label"

> Also for the Location and Description parameters I would recommend the unit to be http://vocab.nerc.ac.uk/collection/P06/current/XXXX/

Happy with that

**Comment by gwemon** [comment]
Thanks @adamml 
The Marine Strategy Framework Directive broad habitat types (Commission Decision (EU) 2017/848) mentions a number of broad habitat types under the Pelagic habitat Theme p69 and the Benthic habitat Theme Table 2 p70
Pelagic broad habitat types include: variable salinity (i.e. estuarine plumes that extend beyond  waters designated as Transitional Waters under Directive 2000/60/EC), coastal, shelf and oceanic/beyond shelf. Benthic broad habitat types include a whole list that we would really expect to be be publised somewhere. If I cannot find a source, I'll simply point to this Table 2 in this official document for the time being.

**Comment by adamml** [comment]
Agreed.

I looked hard for an online resource for Benthic Habitats, but couldn't find one.

I've mocked up a resource here https://irishmarineinstitute.github.io/national-oceanographic-data-centre/html/msfd-broad-scale-habitats.html

**Comment by gwemon** [comment]
I contacted EMODnet Seabed Habitat and there is a published resource already on EIONET: http://dd.eionet.europa.eu/vocabulary/msfd/broadHabitatTypes
I think it's got it all... I'll refer to this version in the description of the new S05 and the new P01 codes.

**Comment by adamml** [comment]
Sounds great - thanks @gwemon

**Comment by gwemon** [comment]
Dear @adamml, these new P01 terms have now been created. Please check the following URLs after 2UTC today and let me know if there are any issues.
vocab.nerc.ac.uk/collection/P01/current/MSPAHAB1
vocab.nerc.ac.uk/collection/P01/current/MSPDHAB1
vocab.nerc.ac.uk/collection/P01/current/MSPGLHA1
Sorry for the long wait.

**Comment by adamml** [comment]
Thanks @gwemon. I'm not seeing those codes on request to the NVS - I'm getting a 400 error `Concept does not exist or is not visible`

Was there an issue with the NERC Vocab Server publication run?

**Comment by adamml** [comment]
@gwemon all good now. Thanks for all your help with these - be in touch soon (and when we write this up)

**Comment by gwemon** [comment]
Yes sorry, the links provided in my original message were not correct. They've now been amended. Thanks @adamml
