### ISSUE TITLE
NTR: Biological Parameters (BODCNVS-727)

### ISSUE THREAD

**Issue by tkeena** [nvs-vocabs/P01#36]
Hi,

Could I request the following terms please:

Abundance of Scomber scombrus (ITIS: 172414: WoRMS 127023) [Stage: eggs] in the water body
Abundance of Trachurus trachurus (ITIS: 168588: WoRMS 126822)[Stage: eggs] in the water body

Many thanks,
Tara

**Comment by gwemon** [comment]
Hi Tara @tkeena , thank you for your request. 
These two species are already defined in the S25 vocabulary so you should be able to create their corresponding biological entities for "Stage= eggs" using the Vocab Builder for biological entity concepts (https://www.bodc.ac.uk/resources/vocabularies/vocabulary_builder/bioentrf/ - remembering to login first in order to be able to submit) . Would you mind doing this and and let me know if you have any issues?

With regards to the P01 codes, I suggest to  stay consistent with existing code and explicitly state "Abundance of X per unit volume of the water body" (if this is the case which I guess it is). 

We will associate these new codes with the following terms:
P02 grouping: http://vocab.nerc.ac.uk/collection/P02/current/FATX/
Suggested units: http://vocab.nerc.ac.uk/collection/P06/current/UCPL/

**Comment by tkeena** [comment]
Hi Gwen @gwemon 

Thanks for your reply on this. I've submitted the two terms in the Vocab Builder for biological entity concepts. Once they are created will I then create the term using the vocab builder? 

I had originally included 'in the water body' instead of 'per unit volume of the water body' as these parameters will be applied to fishery survey datasets where the abundance of the eggs is recorded using a plankton sampler trawled through the water so I wasn't sure if 'in the water body' was more suitable? Thanks again. Tara.

**Comment by gwemon** [comment]
Thanks Tara @tkeena - could you say what units are used to report these data? This will help us decide how the P01 should be modelled. Many thanks, Gwen.

**Comment by gwemon** [comment]
@tkeena Hi Tara, my apologies for the delay in responding to your request. The biological entities have now been created. @danibodc will now take over with the creation of the appropriate P01 codes.

**Comment by danibodc** [comment]
The following P01 terms have now been created:

A9241SC1 Count of Scomber scombrus (ITIS: 172414: WoRMS 127023) [Stage: eggs]
A9242TR1 Count of Trachurus trachurus (ITIS: 168588: WoRMS 126822) [Stage: eggs]

We are investigating an issue that is preventing new codes going live - I will update this ticket once this is resolved.

**Comment by danibodc** [comment]
These codes are now live:

http://vocab.nerc.ac.uk/collection/P01/current/A9241SC1/
http://vocab.nerc.ac.uk/collection/P01/current/A9242TR1/

**Comment by tkeena** [comment]
Great! Thank you Dani and Gwen for creating those.
