### ISSUE TITLE
Equivalent Spherical Diameter

### ISSUE THREAD

**Issue by PatriciaCabrera** [nvs-vocabs/P01#37]
Hello,

Would it be possible to request the following parameter?

Equivalent Spherical Diameter or ESD. 
References: 
1. Jennings, B. R. and Parslow, K. (1988) Particle Size Measurement: The Equivalent Spherical Diameter. Proceedings of the Royal Society of London. Series A 419, 137-149
2. http://thesauri.lifewatchitaly.eu/PhytoTraits/index.php?tema=18&/equivalent-spherical-diameter

Thank you,
Patricia

**Comment by gwemon** [comment]
Hello @PatriciaCabrera. 
Thank you for your request. The P01 vocabulary is used to define parameters or observed variables according to a semantic model which requires to have, at a minimum, a combination of terms related to the property observed and the object and/or matrix targeted. So in the present case, "Equivalent Spherical Diameter" would be the property (defined in [S06 controlled vocabulary](https://www.bodc.ac.uk/resources/vocabularies/vocabulary_search/S06/)). In order to define a P01 you will need to specify to what this property applies to: example particles in the sediment or particles in the water body.

I have checked S06 and we do not yet have a record for Equivalent Spherical Diameter so I will add it.

**Comment by PatriciaCabrera** [comment]
Hello @gwemon, 

Thank you for your explanation and for adding ESD to S06. 

Cheers,
Patricia

**Comment by danibodc** [comment]
A new S06 term has now been created:

S0600260 - Equivalent spherical diameter

Description: The diameter of a spherical particle of equivalent volume which will give identical geometric, optical, electrical or aerodynamic behaviour to that of the particle (non-spherical) being examined, sometimes referred to as the Stokes diameter for particles in non-turbulent flows (Source: IUPAC (1990), https://doi.org/10.1351/pac199062112167).

This is now live on the NVS:
http://vocab.nerc.ac.uk/collection/S06/current/S0600260/

**Comment by gwemon** [comment]
@PatriciaCabrera I have just realised that the P01 code was never created for this property. Please use 
OBSINESD	Equivalent spherical diameter of biological entity specified elsewhere
This code will be live in the P01 vocab after 6:30AM UTC tomorrow.

**Comment by PatriciaCabrera** [comment]
@gwemon Ok, thanks!
