### ISSUE TITLE
NTR: Biomass as nitrogen of Deep Seagrass per unit area of the sea surface

### ISSUE THREAD

**Issue by dr-shorthair** [nvs-vocabs/P01#46]
Symbol: **SGD**

Units: **g.m-2**

Definition: Concentration of nitrogen biomass per m<sup>2</sup> of a seagrass form parameterised to be similar to _Halophila deciphens_. This form captures light after it has passed through the _Zostera_ and _Halophila ovalis_ seagrass form. 

Source: https://doi.org/10.5194/gmd-13-4503-2020 **Supplement** _Table 7_ https://gmd.copernicus.org/articles/13/4503/2020/gmd-13-4503-2020-supplement.zip

**Comment by dr-shorthair** [comment]
I suppose we need _Halophila deciphens_ added to S25 to support this?

**Comment by gwemon** [comment]
@dr-shorthair please could you confirm that "deciphens" is "decipiens" (http://www.marinespecies.org/aphia.php?p=taxdetails&id=145713)?

**Comment by markebaird** [comment]
Just joining this discussion. Thank you for designing a vocab entry to align with our model. It does look like the correct spelling is decipiens, so please use that. Per unit area of seabed would be clearest.

Two broader points:
1. The symbol SGD is unique to our study, and really comes from the variable name in the code. It is not like NO3 for nitrate, which will be universally used.
2. For the vocab purposes, I wonder whether "Concentration of model nitrogen biomass" might help to distinguish between model quantities and observed quantities. Sometimes we like to pretend model and observed quantities are identical, and sometime we realise they are not.
3. I will contact Simon Cox and have a philosophical discussion to help me better contribute to these discussions.

**Comment by dr-shorthair** [comment]
Thx @markebaird 
Also look at #43 #44 #45 #47 which were taken from your work

**Comment by dr-shorthair** [comment]
And https://github.com/nvs-vocabs/S25/issues/ for the related 'Biological entities'. 

If you want to get philosophical @markebaird, see this [explanation of the way that P01 definitions are built](https://github.com/nvs-vocabs/P01)

**Comment by gwemon** [comment]
> Just joining this discussion. Thank you for designing a vocab entry to align with our model. It does look like the correct spelling is decipiens, so please use that. Per unit area of seabed would be clearest.
> 
> Two broader points:
> 
> 1. The symbol SGD is unique to our study, and really comes from the variable name in the code. It is not like NO3 for nitrate, which will be universally used.
> 2. For the vocab purposes, I wonder whether "Concentration of model nitrogen biomass" might help to distinguish between model quantities and observed quantities. Sometimes we like to pretend model and observed quantities are identical, and sometime we realise they are not.
> 3. I will contact Simon Cox and have a philosophical discussion to help me better contribute to these discussions.

Thank you @markebaird 1) noted that "decipiens" is the correct spelling; 2) we are trying to make the P01 term applicable to all aquatic systems whether marine or freshwater hence why we would use "bed" instead of "seabed", however we could  mention "seabed" in the definition of the parameter code to clarify the context; 3) I agree that it is good to specify that the quantity is modelled, and we already have a [term](http://vocab.nerc.ac.uk/collection/S04/current/S041014/) for this. So if we apply this we would get a new P01 concept which once concatenated would look something like:

"Biomass as nitrogen of Halophila decipiens per unit area of the bed by model prediction"

The definition could be: "The mass of nitrogen contributed by Halophira decipiens, a representative species of deep seagrass, in a unit area of seabed based on computation by model prediction."

Would this work?

**Comment by dr-shorthair** [comment]
Is this issue resolved by https://github.com/nvs-vocabs/ereefs/issues/5 ?

**Comment by markebaird** [comment]
I think it is.
