### ISSUE TITLE
NTR: Carbon biomass (calculated) of biological entity specified elsewhere per unit area of the bed (BODCNVS-1859)

### ISSUE THREAD

**Issue by meliezer** [nvs-vocabs/P01#59]
Hello,
The vocab builder didn't allow me specifying Carbon biomass, so I ask here.
P06: http://vocab.nerc.ac.uk/collection/P06/current/UGMC/
P02: http://vocab.nerc.ac.uk/collection/P02/current/BPRP/
This term is similar to http://vocab.nerc.ac.uk/collection/P01/current/SDBIOL12/

Best,
Menashè

**Comment by dr-shorthair** [comment]
Is this similar to 'Biomass as Nitrogen' required for #43 #44 #45 #46 #47 ?

**Comment by meliezer** [comment]
> Is this similar to 'Biomass as Nitrogen' required for #43 #44 #45 #46 #47 ?

No.

**Comment by gwemon** [comment]
Hi @meliezer, the P01 code http://vocab.nerc.ac.uk/collection/P01/current/SDBIOL12/ is still unconstrained against the P01 semantic model. i.e. it is one of the remaining terms still waiting to be "migrated" to the new model. So what I think @dr-shorthair meant is that the preflabel should be constructed in a similar way to what we are proposing for the range of "Biomass as nitrogen" terms requested in those tickets. It is also related to another request we receive for Leucine uptake by bacteria expressed as amount of carbon incorporated instead of amount of leucine taken up (see my comment https://github.com/nvs-vocabs/P01/issues/58#issuecomment-776637520).

**Comment by gwemon** [comment]
So if we follow this logic the SDBIOL12 and your new code would be of the form:

Biomass as carbon of biological entity specified elsewhere per unit area of the bed

I would also be keen to migrate the "calculated" out of the property definition and into the data processing method description  defined in the S05 vocabulary. Something along the lines of: 
"computation from cell counts and published conversion factors"?

**Comment by gwemon** [comment]
Relevant to https://github.com/nvs-vocabs/OBISVocabs/issues/2

**Comment by meliezer** [comment]
Hi @gwemon, I understand. Do you use 'published' instead of 'mentioned elsewhere' since you assume there are scientific papers supporting the conversion factors?

**Comment by gwemon** [comment]
I based my definition on what was used for the existing code (http://vocab.nerc.ac.uk/collection/P01/current/SDBIOL12/ ) however we could just simply say "computation from cell counts"? We could specify in the definition that the source of the conversion factors is expected to be provided in the methodology?

**Comment by meliezer** [comment]
Good idea!

**Comment by gwemon** [comment]
The code S050231 has been created and has been queued for publication into http://vocab.nerc.ac.uk/collection/S05/current/

**Comment by dr-shorthair** [comment]
Should this issue be closed? https://vocab.nerc.ac.uk/collection/S05/current/S050231/

**Comment by jakjonbodc** [comment]
Created new P01 BCBIOLEA - Biomass as carbon of biological entity specified elsewhere per unit area of the bed by computation of carbon biomass using the equation of Alcaraz et al. (2003)

http://vocab.nerc.ac.uk/collection/P01/current/BCBIOLEA/
