### ISSUE TITLE
NTR: Size of biological entity specified elsewhere (BODCNVS-989)

### ISSUE THREAD

**Issue by meliezer** [nvs-vocabs/P01#65]
This term request is for having an ID to mention in eMoF of OBIS, but I think it would be useful also for BODV of SeaDataNet.
Initially I thought to add 'category', but I see that the related collection (S09) includes also specific sizes.
P06 would be naturally XXXX since the terms are textual, e.g. 'small'.

**Comment by gwemon** [comment]
@meliezer Thanks you for your request. Yes "Size category" is good. I think that if the result of this P01 is intended to be a S09 concept then we should specify it otherwise there is a risk of users using this term for any free-text information. Would you agree? i.e. specify S09 as part of the data_proc as we have done for some other P01 codes where the result is intended to be drawn from a specific controlled vocabulary.

**Comment by meliezer** [comment]
@gwemon , Yes, but I have a dataset with many specific sizes. Should I ask for new S09 terms, or shall we have two different new terms: one is size category (S09 related) and the other is a numeric size?
You may want to verify it also with Obis. @rubenpp7, What is your opinion?

**Comment by gwemon** [comment]
@meliezer the new P01 "Size category of biological entity specified elsewhere" once created, should only be used for situation where biological entities are grouped according to size categories. It should not be used for situation where the result is a real number with a unit of "length".
I think it would be a mistake to create a P01 terms for "Size of biological entity specified elsewhere" simply because this is too vague... if it is a length then we should use "Length of..." if it is a diameter then we should use "Diameter of..." if it is a width then we should use "Width of...", etc.
Does that make sense in the context of your dataset?

**Comment by meliezer** [comment]
@gwemon it's a good question, but I should ask the same for size mentioned in P01 terms related to S09 terms like http://vocab.nerc.ac.uk/collection/S09/current/S0921/
Specifically for my dataset, I believe it's length, but I'm waiting for a confirmation.

**Comment by gwemon** [comment]
@meliezer yes that's a very good point your making. The key question here is: are the specific sizes you have in your dataset the result of the observation or are they used to describe the observed object? For example, consider the difference between: "Size of species XX individuals"=15 um and "Abundance of species XX individuals of 15um size range".
Thank you for your input as this makes me realise that we really need to improve this part of the model and the definitions for these terms as I would have considered any info in S11 to be a "nominal size range" but this is not obvious to the external user. Hence there is a real risk that the semantic "building-blocks" that are defined in order to be used for the construction of a P01 code be used for something they were not intended for. All the terms defined in S11 are used to construct a P01 code where the size/size range/nominal is one of the descriptive element of the biological entity see e.g. the P01 terms linked to http://vocab.nerc.ac.uk/collection/S25/current/BE004544/

**Comment by meliezer** [comment]
@gwemon The sizes are used to describe the observed object, based on actual measurement.
Is there an alternative vocabulary I could use? I have both cases of 'small' like terms, size ranges and specific sizes.
Do you mean that since S09 is used as a building block, it's better speaking about size and not make a specific definition, otherwise, you'll have an overpopulation of terms?
Anyway, end user looks for a good vocabulary and then uses it in case the term is right.

**Comment by gwemon** [comment]
Thank you @meliezer Could you send me an example dataset by email where the S09 terms are needed so that I make sure I am answering your question correctly?

**Comment by meliezer** [comment]
@gwemon sent. Thank you!

**Comment by meliezer** [comment]
@gwemon I confirm that for my dataset size means length.
