### ISSUE TITLE
NTR: Skin temperature of the water body (BODCNVS-1079)

### ISSUE THREAD

**Issue by dr-shorthair** [nvs-vocabs/P01#76]
"Skin temperature of the water body measure by Advanced Very High Resolution Radiometer (AVHRR)" 
- see http://vocab.aodn.org.au/def/discovery_parameter/entity/97

**Comment by gwemon** [comment]
@dr-shorthair this code already exists (http://vocab.nerc.ac.uk/collection/P01/current/TEMPAV01/) however it has not been mapped to our PUV semantic model yet and this is why you might not have found it. My guess is that it's been on hold because we needed to take a decision on how to model "Skin temperature".
So your request will prompt us to do that. I think that we could model it as "[Temperature](http://vocab.nerc.ac.uk/collection/S06/current/S0600082/) of sea surface microlayer of the water body by Advanced Very High Resolution Radiometer (AVHRR)"
I prefer sea surface microlayer (see e.g. https://en.wikipedia.org/wiki/Sea_surface_microlayer) because it is transferrable to more parameter concepts and processes associated with ocean-atmosphere exchanges. 
If this is approved then we will need to define a new S29 physical entity for "sea surface microlayer" or maybe just "surface microlayer" to make it applicable to any kinds of water body. 
@roy-lowry, does that sound right?

**Comment by dr-shorthair** [comment]
@sharon-tickell @markebaird

**Comment by roy-lowry** [comment]
@gwemon Sounds reasonable. Think I'd prefer 'surface microlayer' to 'sea surface microlayer'.

**Comment by gwemon** [comment]
@roy-lowry Am I correct to think that this new code could have a sameAs relationship with CF Standard Name  http://vocab.nerc.ac.uk/collection/P07/current/CFV9N2/? but it would not map to http://vocab.nerc.ac.uk/collection/P07/current/CFV9N3/?

**Comment by roy-lowry** [comment]
@gwemon Yes. We have three 'skin-temperature' P01 codes. Two are for infrared radiometers (PSSTRT01 and TEMPAV01) and are sameAs CFV9N2. The third (TEMPMWRD) is sameAs CFV9N3 and should maybe be modified to use the CF term 'subskin temperature'.

**Comment by gwemon** [comment]
Thanks @roy-lowry. These 3 P01 codes have now been migrated to the GP_MODEL and mapped to their CF Standard Name equivalent. The changes will be published on the NVS tomorrow.
